[package]
name = "ec"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1.3"
array2d = "0.3.2"
intervallum = "1.4.4"
log = "0.4.27"
trie-rs = "0.4.2"

[dev-dependencies]
test-log = "0.2.18"
